from MainWindowWithTabs import *
from AddWriterWindow import *
from AddBookWindow import *
from BooksWindow import *
from QuizWindow import *
from LibraryTab import *
from MainWindow import *
from database import *
from GameTab import *
from QuizTab import *
from MapTab import *
from dTab import *
from Auth import *
